### 1.	Write a Python Program to Add Two Matrices?

In [21]:
import numpy as np
def mat_add(a,b):
    try:
        summ=np.zeros(a.shape)
        for i in range(len(a)):
            for j in range(len(a[0])):
                summ[i][j]=a[i][j] + b[i][j]
        return summ
    except Exception as e:
        print('Both matrices should be compatible. Error msg: {}'.format(e))

In [24]:
arr1=np.asarray([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.asarray([[9,1,6],[8,3,6],[8,5,0]])

In [25]:
mat_add(arr1,arr2)

array([[10.,  3.,  9.],
       [12.,  8., 12.],
       [15., 13.,  9.]])

### 2.	Write a Python Program to Multiply Two Matrices?

In [26]:
import numpy as np
def mat_mul(a,b):
    try:
        mul=np.zeros(a.shape)
        for i in range(len(a)):
            for j in range(len(b[0])):
                for k in range(len(b)):
                    mul[i][j]+=a[i][k] * b[k][j]
        return mul
    except Exception as e:
        print('Both matrices should be compatible. Error msg: {}'.format(e))

In [27]:
arr1=np.asarray([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.asarray([[9,1,6],[8,3,6],[8,5,0]])

In [29]:
mat_mul(arr1,arr2)

array([[ 49.,  22.,  18.],
       [124.,  49.,  54.],
       [199.,  76.,  90.]])

### 3.	Write a Python Program to Transpose a Matrix?

In [30]:
import numpy as np
def mat_transpose(a):
    try:
        t_mat=np.zeros(a.shape)
        for i in range(len(a)):
            for j in range(len(a[0])):
                t_mat[i][j]=a[j][i]
        return t_mat
    except Exception as e:
        print('Error msg: {}'.format(e))

In [31]:
arr1=np.asarray([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
mat_transpose(arr1)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [39]:
def sort_words(a):
    try:
        b=a.lower().split()
        b.sort()
        return b
    except Exception as e:
        print('Error msg: {}'.format(e))

In [40]:
a="It has been a wonderful day"

In [41]:
 sort_words(a)

['a', 'been', 'day', 'has', 'it', 'wonderful']

### 5.	Write a Python Program to Remove Punctuation From a String?

In [42]:
def remove_punc(a):
    try:
        remover='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
        final=''
        for i in a:
            if i not in remover:
                final+=i
        return final
    except Exception as e:
        print('Error msg: {}'.format(e))

In [43]:
sentence='Happy Birthday!! Have a good day, have fun :-)'

In [44]:
remove_punc(sentence)

'Happy Birthday Have a good day have fun '